/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package imageapplication;

import Effects.Posterize;
import Effects.Treshold;
import Effects.Saturation;
import Effects.RedAdjust;
import Effects.Hue;
import Effects.GreyScale;
import Effects.GreenAdjust;
import Effects.Granulate;
import Effects.Contrast;
import Effects.BlueAdjust;
import Effects.AutoColor;
import Effects.AutoBrighten;
import Effects.AutoContrast;
import Effects.Invert;
import Effects.Effects;
import Effects.Brighten;
import Effects.ConvoEffect;
import Effects.DustFilter;
import java.awt.AlphaComposite;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.MediaTracker;
import java.awt.Point;
import java.awt.RenderingHints;
import java.awt.color.ColorSpace;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.geom.AffineTransform;
import java.awt.image.AffineTransformOp;
import java.awt.image.BufferedImage;
import java.awt.image.BufferedImageOp;
import java.awt.image.ColorConvertOp;
import java.awt.image.ConvolveOp;
import java.awt.image.CropImageFilter;
import java.awt.image.FilteredImageSource;
import java.awt.image.ImageFilter;
import java.awt.image.Kernel;
import java.awt.image.MemoryImageSource;
import java.awt.image.PixelGrabber;
import java.awt.image.RenderedImage;
import java.io.File;
import java.io.FileFilter;
import java.io.IOException;
import java.lang.String;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JSlider;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author Govind
 */
public class MainFrame extends javax.swing.JFrame implements ChangeListener, MouseListener {

    ImageViewer imageviewer1;
    int pixels[];
    Effects CurrEffect;
    ConvoEffect ConvEffect;
    private BufferedImage bufim;
    int mx1,my1,mx2,my2,ismouseclicked=0,crop=1;

    /** Creates new form MainFrame */
    public MainFrame() {
        initComponents();
        AdjModule1.setLocation(200,200);
        AdjModule1.setSize(320, 150);
        AdjModule1.setTitle("Adjust");
        AdjModule1.setClosable(true);

        jSlider1.setMaximum(256);
        jSlider1.setMinimum(-150);
        jSlider1.setMajorTickSpacing(50);
        jSlider1.setMinorTickSpacing(10);
        jSlider1.setValue(50);
        jSlider1.setPaintTicks(true);
        jSlider1.addChangeListener(this);
        this.add(AdjModule1);

    }

    private void InitPixels(Image image) {
        int width = image.getWidth(null);
        int height = image.getHeight(null);
        pixels = new int[width * height];

        PixelGrabber pg = new PixelGrabber(image, 0, 0, width, height, pixels, 0, width);
  
        try {
            pg.grabPixels();
        } catch (InterruptedException ex) {
            ex.printStackTrace();
        }

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ConfirmDialog = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        ResizeDialog = new javax.swing.JDialog();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        AdjModule1 = new javax.swing.JInternalFrame();
        jSlider1 = new javax.swing.JSlider();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        AutomaticControlsPanel = new javax.swing.JPanel();
        AutoBrightenButton = new javax.swing.JButton();
        AutoColorButton = new javax.swing.JButton();
        AutoContrastButton = new javax.swing.JButton();
        DustFilterButton = new javax.swing.JButton();
        GlowButton = new javax.swing.JButton();
        AutoEnhanceButton = new javax.swing.JButton();
        ManualControlsPanel = new javax.swing.JPanel();
        BrightenButton = new javax.swing.JButton();
        ContrastButton = new javax.swing.JButton();
        GreyScaleButton = new javax.swing.JButton();
        InvertButton = new javax.swing.JButton();
        PosterizeButton = new javax.swing.JButton();
        TresholdButton = new javax.swing.JButton();
        SharpenButton = new javax.swing.JButton();
        BlurButton = new javax.swing.JButton();
        BumpButton = new javax.swing.JButton();
        EdgeDetectButton = new javax.swing.JButton();
        ResizeButton = new javax.swing.JButton();
        EmbossButton = new javax.swing.JButton();
        RedAdjButton = new javax.swing.JButton();
        BlueAdjButton = new javax.swing.JButton();
        GreenAdjButton = new javax.swing.JButton();
        HueButton = new javax.swing.JButton();
        SaturationButton = new javax.swing.JButton();
        GranulateButton = new javax.swing.JButton();
        CropButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        OpenMenuItem = new javax.swing.JMenuItem();
        SaveMenuItem = new javax.swing.JMenuItem();
        QuitMenuItem = new javax.swing.JMenuItem();
        EditMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        jLabel1.setText("Do You wish to Apply This Effect ?");

        jButton6.setText("Cancel");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton5.setText("Apply");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ConfirmDialogLayout = new javax.swing.GroupLayout(ConfirmDialog.getContentPane());
        ConfirmDialog.getContentPane().setLayout(ConfirmDialogLayout);
        ConfirmDialogLayout.setHorizontalGroup(
            ConfirmDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConfirmDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ConfirmDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ConfirmDialogLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap())
                    .addGroup(ConfirmDialogLayout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6)
                        .addGap(18, 18, 18))))
        );
        ConfirmDialogLayout.setVerticalGroup(
            ConfirmDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ConfirmDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(ConfirmDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addContainerGap())
        );

        jLabel2.setText("Width: ");

        jLabel3.setText("Height:");

        jLabel4.setText("Enter the new dimensions for the image:");

        jButton16.setText("Apply");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton17.setText("Cancel");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ResizeDialogLayout = new javax.swing.GroupLayout(ResizeDialog.getContentPane());
        ResizeDialog.getContentPane().setLayout(ResizeDialogLayout);
        ResizeDialogLayout.setHorizontalGroup(
            ResizeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResizeDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ResizeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(ResizeDialogLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(ResizeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ResizeDialogLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ResizeDialogLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(48, 48, 48)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ResizeDialogLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jButton16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jButton17)
                .addGap(32, 32, 32))
        );
        ResizeDialogLayout.setVerticalGroup(
            ResizeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResizeDialogLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ResizeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ResizeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(ResizeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton17)
                    .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        jButton27.setText("Apply");
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });

        jButton28.setText("Cancel");
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AdjModule1Layout = new javax.swing.GroupLayout(AdjModule1.getContentPane());
        AdjModule1.getContentPane().setLayout(AdjModule1Layout);
        AdjModule1Layout.setHorizontalGroup(
            AdjModule1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdjModule1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(AdjModule1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(AdjModule1Layout.createSequentialGroup()
                        .addComponent(jButton27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton28))
                    .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        AdjModule1Layout.setVerticalGroup(
            AdjModule1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdjModule1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(AdjModule1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton27)
                    .addComponent(jButton28))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AUTIMEN - Auto Image Enhance !!!");
        setResizable(false);

        AutomaticControlsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Automatic Controls"));

        AutoBrightenButton.setText("AutoBrighten");
        AutoBrightenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AutoBrightenButtonActionPerformed(evt);
            }
        });

        AutoColorButton.setText("Auto Color");
        AutoColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AutoColorButtonActionPerformed(evt);
            }
        });

        AutoContrastButton.setText("Auto Contrast");
        AutoContrastButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AutoContrastButtonActionPerformed(evt);
            }
        });

        DustFilterButton.setText("Dust Filter");
        DustFilterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DustFilterButtonActionPerformed(evt);
            }
        });

        GlowButton.setText("Glow");
        GlowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GlowButtonActionPerformed(evt);
            }
        });

        AutoEnhanceButton.setText("AutoEnhancement");
        AutoEnhanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AutoEnhanceButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AutomaticControlsPanelLayout = new javax.swing.GroupLayout(AutomaticControlsPanel);
        AutomaticControlsPanel.setLayout(AutomaticControlsPanelLayout);
        AutomaticControlsPanelLayout.setHorizontalGroup(
            AutomaticControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AutomaticControlsPanelLayout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(AutoBrightenButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AutoColorButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AutoContrastButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GlowButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DustFilterButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AutoEnhanceButton)
                .addContainerGap(669, Short.MAX_VALUE))
        );
        AutomaticControlsPanelLayout.setVerticalGroup(
            AutomaticControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AutomaticControlsPanelLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(AutomaticControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AutoBrightenButton)
                    .addComponent(AutoColorButton)
                    .addComponent(AutoContrastButton)
                    .addComponent(GlowButton)
                    .addComponent(DustFilterButton)
                    .addComponent(AutoEnhanceButton))
                .addGap(36, 36, 36))
        );

        ManualControlsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Manual Controls"));

        BrightenButton.setText("Brighten");
        BrightenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrightenButtonActionPerformed(evt);
            }
        });

        ContrastButton.setText("Contrast");
        ContrastButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContrastButtonActionPerformed(evt);
            }
        });

        GreyScaleButton.setText("GreyScale");
        GreyScaleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GreyScaleButtonActionPerformed(evt);
            }
        });

        InvertButton.setText("Invert");
        InvertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InvertButtonActionPerformed(evt);
            }
        });

        PosterizeButton.setText("Posterize");
        PosterizeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PosterizeButtonActionPerformed(evt);
            }
        });

        TresholdButton.setText("Treshold");
        TresholdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TresholdButtonActionPerformed(evt);
            }
        });

        SharpenButton.setText("Sharpen");
        SharpenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SharpenButtonActionPerformed(evt);
            }
        });

        BlurButton.setText("Blur");
        BlurButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlurButtonActionPerformed(evt);
            }
        });

        BumpButton.setText("Bump");
        BumpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BumpButtonActionPerformed(evt);
            }
        });

        EdgeDetectButton.setText("Edge Detection");
        EdgeDetectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdgeDetectButtonActionPerformed(evt);
            }
        });

        ResizeButton.setText("Resize");
        ResizeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResizeButtonActionPerformed(evt);
            }
        });

        EmbossButton.setText("Emboss");
        EmbossButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmbossButtonActionPerformed(evt);
            }
        });

        RedAdjButton.setText("Red Adjust");
        RedAdjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RedAdjButtonActionPerformed(evt);
            }
        });

        BlueAdjButton.setText("Blue Adjust");
        BlueAdjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlueAdjButtonActionPerformed(evt);
            }
        });

        GreenAdjButton.setText("Green Adjust");
        GreenAdjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GreenAdjButtonActionPerformed(evt);
            }
        });

        HueButton.setText("Hue Adjust ");
        HueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HueButtonActionPerformed(evt);
            }
        });

        SaturationButton.setText("Saturation Adjust");
        SaturationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaturationButtonActionPerformed(evt);
            }
        });

        GranulateButton.setText("Granulate");
        GranulateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GranulateButtonActionPerformed(evt);
            }
        });

        CropButton.setText("Crop");
        CropButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CropButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ManualControlsPanelLayout = new javax.swing.GroupLayout(ManualControlsPanel);
        ManualControlsPanel.setLayout(ManualControlsPanelLayout);
        ManualControlsPanelLayout.setHorizontalGroup(
            ManualControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManualControlsPanelLayout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addGroup(ManualControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ManualControlsPanelLayout.createSequentialGroup()
                        .addComponent(BrightenButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ContrastButton))
                    .addGroup(ManualControlsPanelLayout.createSequentialGroup()
                        .addComponent(ResizeButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RedAdjButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ManualControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ManualControlsPanelLayout.createSequentialGroup()
                        .addComponent(BlueAdjButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GreenAdjButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(HueButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SaturationButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GranulateButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CropButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EmbossButton))
                    .addGroup(ManualControlsPanelLayout.createSequentialGroup()
                        .addComponent(GreyScaleButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(InvertButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PosterizeButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TresholdButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SharpenButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BlurButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BumpButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EdgeDetectButton)))
                .addContainerGap(447, Short.MAX_VALUE))
        );
        ManualControlsPanelLayout.setVerticalGroup(
            ManualControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManualControlsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ManualControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ManualControlsPanelLayout.createSequentialGroup()
                        .addGroup(ManualControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BrightenButton)
                            .addComponent(ContrastButton))
                        .addGap(18, 18, 18)
                        .addGroup(ManualControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ResizeButton)
                            .addComponent(RedAdjButton)))
                    .addGroup(ManualControlsPanelLayout.createSequentialGroup()
                        .addGroup(ManualControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GreyScaleButton)
                            .addComponent(InvertButton)
                            .addComponent(PosterizeButton)
                            .addComponent(TresholdButton)
                            .addComponent(SharpenButton)
                            .addComponent(BlurButton)
                            .addComponent(BumpButton)
                            .addComponent(EdgeDetectButton))
                        .addGap(18, 18, 18)
                        .addGroup(ManualControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BlueAdjButton)
                            .addComponent(GreenAdjButton)
                            .addComponent(HueButton)
                            .addComponent(SaturationButton)
                            .addComponent(GranulateButton)
                            .addComponent(CropButton)
                            .addComponent(EmbossButton))))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        FileMenu.setText("File");

        OpenMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        OpenMenuItem.setText("Open");
        OpenMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenMenuItemActionPerformed(evt);
            }
        });
        FileMenu.add(OpenMenuItem);

        SaveMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        SaveMenuItem.setText("Save");
        SaveMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveMenuItemActionPerformed(evt);
            }
        });
        FileMenu.add(SaveMenuItem);

        QuitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        QuitMenuItem.setText("Quit");
        QuitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitMenuItemActionPerformed(evt);
            }
        });
        FileMenu.add(QuitMenuItem);

        jMenuBar1.add(FileMenu);

        EditMenu.setText("Help");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Contents");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        EditMenu.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("About Us");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        EditMenu.add(jMenuItem2);

        jMenuBar1.add(EditMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AutomaticControlsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ManualControlsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(AutomaticControlsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 506, Short.MAX_VALUE)
                .addComponent(ManualControlsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OpenMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenMenuItemActionPerformed
        imageviewer1 = new ImageViewer();
        imageviewer1.addMouseListener(this);
        this.add(imageviewer1);
        this.pack();
        imageviewer1.setVisible(true);
        InitPixels(imageviewer1.image);
    // TODO add your handling code here:
}//GEN-LAST:event_OpenMenuItemActionPerformed

    private void BrightenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrightenButtonActionPerformed
        AdjModule1.setVisible(true);
        CurrEffect = new Brighten();      
    // TODO add your handling code here:
}//GEN-LAST:event_BrightenButtonActionPerformed

    private void ContrastButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContrastButtonActionPerformed
        AdjModule1.setVisible(true);
        CurrEffect = new Contrast();
    // TODO add your handling code here:
}//GEN-LAST:event_ContrastButtonActionPerformed

    private void GreyScaleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GreyScaleButtonActionPerformed
        AdjModule1.setVisible(true);
        CurrEffect = new GreyScale();
        // TODO add your handling code here:
}//GEN-LAST:event_GreyScaleButtonActionPerformed

    private void InvertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InvertButtonActionPerformed
        CurrEffect = new Invert();
        int width = imageviewer1.image.getWidth(null);
        int height = imageviewer1.image.getHeight(null);
        InitPixels(imageviewer1.image);
        CurrEffect.Filter(pixels, width, height,0);
        
        imageviewer1.image2 = createImage(new MemoryImageSource(width, height, pixels, 0, width));
        ConfirmDialog.setVisible(true);
        ConfirmDialog.setBounds(200,200,250,150);
        imageviewer1.preview();
        // TODO add your handling code here:
}//GEN-LAST:event_InvertButtonActionPerformed

    private void PosterizeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PosterizeButtonActionPerformed
        CurrEffect = new Posterize();
        int width = imageviewer1.image.getWidth(null);
        int height = imageviewer1.image.getHeight(null);
        InitPixels(imageviewer1.image);
        CurrEffect.Filter(pixels, width, height,0);

        imageviewer1.image2 = createImage(new MemoryImageSource(width, height, pixels, 0, width));
        ConfirmDialog.setVisible(true);
        ConfirmDialog.setBounds(200,200,250,150);
        imageviewer1.preview();// TODO add your handling code here:
}//GEN-LAST:event_PosterizeButtonActionPerformed

    private void TresholdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TresholdButtonActionPerformed
        CurrEffect = new Treshold();
        int width = imageviewer1.image.getWidth(null);
        int height = imageviewer1.image.getHeight(null);
        InitPixels(imageviewer1.image);
        CurrEffect.Filter(pixels, width, height,0);

        imageviewer1.image2 = createImage(new MemoryImageSource(width, height, pixels, 0, width));
        ConfirmDialog.setVisible(true);
        ConfirmDialog.setBounds(200,200,220,150);
        imageviewer1.preview();
        // TODO add your handling code here:
}//GEN-LAST:event_TresholdButtonActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        imageviewer1.setSize(imageviewer1.image.getWidth(null), imageviewer1.image.getHeight(null));
        imageviewer1.repaint();
        ConfirmDialog.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
     imageviewer1.switchimg();
     imageviewer1.repaint();
     ConfirmDialog.setVisible(false);
    // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void AutoBrightenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AutoBrightenButtonActionPerformed
        CurrEffect = new AutoBrighten();
        int width = imageviewer1.image.getWidth(null);
        int height = imageviewer1.image.getHeight(null);
        InitPixels(imageviewer1.image);
        CurrEffect.Filter(pixels, width, height,0);

        imageviewer1.image2 = createImage(new MemoryImageSource(width, height, pixels, 0, width));
        ConfirmDialog.setVisible(true);
        ConfirmDialog.setBounds(200,200,220,150);
        imageviewer1.preview();
        // TODO add your handling code here:
}//GEN-LAST:event_AutoBrightenButtonActionPerformed

    private void SharpenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SharpenButtonActionPerformed

   ConvEffect = new ConvoEffect("Sharpen");
   imageviewer1.image2=ConvEffect.Filter(imageviewer1.image,this);

        ConfirmDialog.setVisible(true);
        ConfirmDialog.setBounds(200,200,220,150);
        imageviewer1.preview();
        // TODO add your handling code here:
}//GEN-LAST:event_SharpenButtonActionPerformed

    private void BlurButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlurButtonActionPerformed
   ConvEffect = new ConvoEffect("Blur");
   imageviewer1.image2=ConvEffect.Filter(imageviewer1.image,this);

        ConfirmDialog.setVisible(true);
        ConfirmDialog.setBounds(200,200,220,150);
        imageviewer1.preview();
        // TODO add your handling code here:
}//GEN-LAST:event_BlurButtonActionPerformed

    private void BumpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BumpButtonActionPerformed
   ConvEffect = new ConvoEffect("Bump");
   imageviewer1.image2=ConvEffect.Filter(imageviewer1.image,this);

        ConfirmDialog.setVisible(true);
        ConfirmDialog.setBounds(200,200,220,150);
        imageviewer1.preview();
        // TODO add your handling code here:
}//GEN-LAST:event_BumpButtonActionPerformed

    private void EdgeDetectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdgeDetectButtonActionPerformed
   ConvEffect = new ConvoEffect("Edge");
   imageviewer1.image2=ConvEffect.Filter(imageviewer1.image,this);

        ConfirmDialog.setVisible(true);
        ConfirmDialog.setBounds(200,200,220,150);
        imageviewer1.preview();
        // TODO add your handling code here:
}//GEN-LAST:event_EdgeDetectButtonActionPerformed

    private void ResizeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResizeButtonActionPerformed
  
 jSpinner1.setValue(imageviewer1.image.getWidth(null));
 jSpinner2.setValue(imageviewer1.image.getHeight(null));
 ResizeDialog.setVisible(true);
 ResizeDialog.setBounds(200,200,250,200);

        // TODO add your handling code here:
}//GEN-LAST:event_ResizeButtonActionPerformed

    private void EmbossButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmbossButtonActionPerformed
   ConvEffect = new ConvoEffect("Emboss");
   imageviewer1.image2=ConvEffect.Filter(imageviewer1.image,this);

        ConfirmDialog.setVisible(true);
        ConfirmDialog.setBounds(200,200,220,150);
        imageviewer1.preview();   // TODO add your handling code here:
}//GEN-LAST:event_EmbossButtonActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
    float width = imageviewer1.image.getWidth(null);
    float height = imageviewer1.image.getHeight(null);

 bufim = new BufferedImage((int)width,(int)height,BufferedImage.TYPE_INT_RGB);
  Integer w= (Integer) jSpinner1.getValue();
  Integer h= (Integer) jSpinner2.getValue();
 ResizeDialog.setVisible(false);

 float widthratio = (((float)w.doubleValue())/((float)width));float heightratio = ((float)h.intValue())/((float)(height));
 
  Graphics2D g2d = bufim.createGraphics();
  g2d.drawImage(imageviewer1.image,0,0,this);

AffineTransform transform = AffineTransform.getScaleInstance(widthratio, heightratio);
AffineTransformOp op = new AffineTransformOp(transform,AffineTransformOp.TYPE_BILINEAR);

imageviewer1.image = op.filter(bufim, null);

        imageviewer1.setSize(imageviewer1.image.getWidth(null), imageviewer1.image.getHeight(null));
        imageviewer1.repaint();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
ResizeDialog.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void RedAdjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RedAdjButtonActionPerformed
        AdjModule1.setVisible(true);
        CurrEffect = new RedAdjust();
        // TODO add your handling code here:
}//GEN-LAST:event_RedAdjButtonActionPerformed

    private void BlueAdjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlueAdjButtonActionPerformed
        AdjModule1.setVisible(true);
        CurrEffect = new BlueAdjust();  // TODO add your handling code here:
}//GEN-LAST:event_BlueAdjButtonActionPerformed

    private void GreenAdjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GreenAdjButtonActionPerformed
        AdjModule1.setVisible(true);
        CurrEffect = new GreenAdjust();  // TODO add your handling code here:
}//GEN-LAST:event_GreenAdjButtonActionPerformed

    private void HueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HueButtonActionPerformed
   AdjModule1.setVisible(true);
   CurrEffect = new Hue();
 // TODO add your handling code here:
}//GEN-LAST:event_HueButtonActionPerformed

    private void SaturationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaturationButtonActionPerformed
      AdjModule1.setVisible(true);
      CurrEffect = new Saturation();
  // TODO add your handling code here:
}//GEN-LAST:event_SaturationButtonActionPerformed

    private void GranulateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GranulateButtonActionPerformed
        CurrEffect = new Granulate();
        int width = imageviewer1.image.getWidth(null);
        int height = imageviewer1.image.getHeight(null);
        InitPixels(imageviewer1.image);
        CurrEffect.Filter(pixels, width, height,0);

        imageviewer1.image2 = createImage(new MemoryImageSource(width, height, pixels, 0, width));
        ConfirmDialog.setVisible(true);
        ConfirmDialog.setBounds(200,200,220,150);
        imageviewer1.preview();  // TODO add your handling code here:
}//GEN-LAST:event_GranulateButtonActionPerformed

    private void AutoColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AutoColorButtonActionPerformed
        CurrEffect = new AutoColor();
        int width = imageviewer1.image.getWidth(null);
        int height = imageviewer1.image.getHeight(null);
        InitPixels(imageviewer1.image);
        CurrEffect.Filter(pixels, width, height,0);

        imageviewer1.image2 = createImage(new MemoryImageSource(width, height, pixels, 0, width));
        ConfirmDialog.setVisible(true);
        ConfirmDialog.setBounds(200,200,220,150);
        imageviewer1.preview();
        // TODO add your handling code here:
}//GEN-LAST:event_AutoColorButtonActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
     imageviewer1.switchimg();
     imageviewer1.repaint();
     AdjModule1.setVisible(false);
     jSlider1.setValue(50);   
        // TODO add your handling code here:
}//GEN-LAST:event_jButton27ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        imageviewer1.repaint();
        AdjModule1.setVisible(false);
        jSlider1.setValue(50);
       // TODO add your handling code here:
    }//GEN-LAST:event_jButton28ActionPerformed

    @SuppressWarnings("empty-statement")
    private void CropButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CropButtonActionPerformed
   crop=1;
        // TODO add your handling code here:
}//GEN-LAST:event_CropButtonActionPerformed

    private void AutoContrastButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AutoContrastButtonActionPerformed
        CurrEffect = new AutoContrast();
        int width = imageviewer1.image.getWidth(null);
        int height = imageviewer1.image.getHeight(null);
        InitPixels(imageviewer1.image);
        CurrEffect.Filter(pixels, width, height,0);

        imageviewer1.image2 = createImage(new MemoryImageSource(width, height, pixels, 0, width));
        ConfirmDialog.setVisible(true);
        ConfirmDialog.setBounds(200,200,220,150);
        imageviewer1.preview(); // TODO add your handling code here:
}//GEN-LAST:event_AutoContrastButtonActionPerformed

    private void DustFilterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DustFilterButtonActionPerformed
        CurrEffect = new DustFilter();
        int width = imageviewer1.image.getWidth(null);
        int height = imageviewer1.image.getHeight(null);
        InitPixels(imageviewer1.image);
        CurrEffect.Filter(pixels, width, height,0);

        imageviewer1.image2 = createImage(new MemoryImageSource(width, height, pixels, 0, width));
        ConfirmDialog.setVisible(true);
        ConfirmDialog.setBounds(200,200,220,150);
        imageviewer1.preview(); // TODO add your handling code here:
}//GEN-LAST:event_DustFilterButtonActionPerformed

    private void GlowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GlowButtonActionPerformed
   ConvEffect = new ConvoEffect("Glow");
   imageviewer1.image2=ConvEffect.Filter(imageviewer1.image,this);
        ConfirmDialog.setVisible(true);
        ConfirmDialog.setBounds(200,200,220,150);
        imageviewer1.preview();
        // TODO add your handling code here:
}//GEN-LAST:event_GlowButtonActionPerformed

    private void QuitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitMenuItemActionPerformed
this.dispose();// TODO add your handling code here:
}//GEN-LAST:event_QuitMenuItemActionPerformed

    private void SaveMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveMenuItemActionPerformed

 int w = imageviewer1.image.getWidth(null);
 int h = imageviewer1.image.getHeight(null);
        int type = BufferedImage.TYPE_INT_RGB;  // other options
        bufim = new BufferedImage(w, h, type);
        Graphics2D g2 = bufim.createGraphics();
        g2.drawImage(imageviewer1.image, 0, 0, null);
        g2.dispose();
        JFrame f = new JFrame();
        JFileChooser chooser = new JFileChooser();

        chooser.setDialogType( JFileChooser.SAVE_DIALOG ) ;
        chooser.setAcceptAllFileFilterUsed(false);

        chooser.showSaveDialog(f);
        File output = new File(chooser.getSelectedFile().toString());
        
try {
            ImageIO.write(bufim,"jpg", output);  // ignore returned boolean
        } catch(IOException e) {
            System.out.println("Write error for " + output.getPath() +
                               ": " + e.getMessage());
        }
// TODO add your handling code here:
    }//GEN-LAST:event_SaveMenuItemActionPerformed

    private void AutoEnhanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AutoEnhanceButtonActionPerformed
        int width = imageviewer1.image.getWidth(null);
        int height = imageviewer1.image.getHeight(null);
        CurrEffect = new DustFilter();
        InitPixels(imageviewer1.image);
        CurrEffect.Filter(pixels, width, height,0);


for(int i=0;i<1;i++)
{
     ConvEffect = new ConvoEffect("Sharpen");
   imageviewer1.image2=ConvEffect.Filter(imageviewer1.image,this);
    ConvEffect = new ConvoEffect("Blur");
   imageviewer1.image2=ConvEffect.Filter(imageviewer1.image,this);
}
        CurrEffect = new AutoContrast(128,50);
        CurrEffect.Filter(pixels, width, height,0);
        CurrEffect = new AutoColor(20);
        CurrEffect.Filter(pixels, width, height,0);
        CurrEffect = new AutoBrighten(150,20);
        CurrEffect.Filter(pixels, width, height,0);
     ConvEffect = new ConvoEffect("Glow");
   imageviewer1.image2=ConvEffect.Filter(imageviewer1.image,this);

        imageviewer1.image2 = createImage(new MemoryImageSource(width, height, pixels, 0, width));
        ConfirmDialog.setVisible(true);
        ConfirmDialog.setBounds(200,200,220,150);
        imageviewer1.preview();// TODO add your handling code here:
}//GEN-LAST:event_AutoEnhanceButtonActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
new h1().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
new about().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame AdjModule1;
    private javax.swing.JButton AutoBrightenButton;
    private javax.swing.JButton AutoColorButton;
    private javax.swing.JButton AutoContrastButton;
    private javax.swing.JButton AutoEnhanceButton;
    private javax.swing.JPanel AutomaticControlsPanel;
    private javax.swing.JButton BlueAdjButton;
    private javax.swing.JButton BlurButton;
    private javax.swing.JButton BrightenButton;
    private javax.swing.JButton BumpButton;
    private javax.swing.JDialog ConfirmDialog;
    private javax.swing.JButton ContrastButton;
    private javax.swing.JButton CropButton;
    private javax.swing.JButton DustFilterButton;
    private javax.swing.JButton EdgeDetectButton;
    private javax.swing.JMenu EditMenu;
    private javax.swing.JButton EmbossButton;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JButton GlowButton;
    private javax.swing.JButton GranulateButton;
    private javax.swing.JButton GreenAdjButton;
    private javax.swing.JButton GreyScaleButton;
    private javax.swing.JButton HueButton;
    private javax.swing.JButton InvertButton;
    private javax.swing.JPanel ManualControlsPanel;
    private javax.swing.JMenuItem OpenMenuItem;
    private javax.swing.JButton PosterizeButton;
    private javax.swing.JMenuItem QuitMenuItem;
    private javax.swing.JButton RedAdjButton;
    private javax.swing.JButton ResizeButton;
    private javax.swing.JDialog ResizeDialog;
    private javax.swing.JButton SaturationButton;
    private javax.swing.JMenuItem SaveMenuItem;
    private javax.swing.JButton SharpenButton;
    private javax.swing.JButton TresholdButton;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    // End of variables declaration//GEN-END:variables

    public void stateChanged(ChangeEvent e) {
        JSlider slider = (JSlider) e.getSource();
        int value = slider.getValue() - 50;

        int width = imageviewer1.image.getWidth(null);
        int height = imageviewer1.image.getHeight(null);
        InitPixels(imageviewer1.image);
        CurrEffect.Filter(pixels, width, height,value);
        
        imageviewer1.image2 = createImage(new MemoryImageSource(width, height, pixels, 0, width));
        imageviewer1.preview();
       
    }
    public void mouseClicked(MouseEvent e) {
        ismouseclicked=1;
       
    }

    public void mousePressed(MouseEvent e) {
        mx1=e.getX();
        my1=e.getY();
        System.out.println("Pressed at : " + e.getX() + " " +e.getY());
    }

    public void mouseReleased(MouseEvent e) {
        mx2=e.getX();
        my2=e.getY();
        System.out.println("Released at : " + e.getX() + " " + e.getY());
      if(crop==1){
   int width = imageviewer1.image.getWidth(null);
   int height = imageviewer1.image.getHeight(null);

 bufim = new BufferedImage((int)width,(int)height,BufferedImage.TYPE_INT_RGB);

 Graphics2D g2d = bufim.createGraphics();
 g2d.drawImage(imageviewer1.image,0,0,this);
 g2d.draw3DRect(mx1,my1,(mx2-mx1),(my2-my1),true);
 
      imageviewer1.image2=  bufim.getSubimage(mx1,my1,mx2-mx1,my2-my1);
        ConfirmDialog.setVisible(true);
        ConfirmDialog.setBounds(200,200,220,150);
        imageviewer1.setSize(imageviewer1.image2.getWidth(null), imageviewer1.image2.getHeight(null));

      imageviewer1.preview();


 crop=0;
      }

    }

    public void mouseEntered(MouseEvent e) {        
    }

    public void mouseExited(MouseEvent e) {        
    }
}
